"""
Report Generators for Microcontroller API Assistant QA
====================================================

This module generates human-readable reports in Markdown format with:
- Test results summary
- Detailed analysis
- Improvement suggestions
- Performance metrics
"""

from datetime import datetime
from typing import Dict, List
from dataclasses import asdict
from utils.text import sanitize_utf8, clean_for_markdown


class ReportGenerator:
    """Generates comprehensive QA test reports in Markdown format."""
    
    def __init__(self):
        self.report_template = """
# QA Test Report - Microcontroller API Assistant

**Generated:** {timestamp}  
**Test Suite:** {test_suite_name}  
**Total Tests:** {total_tests}  
**Duration:** {duration:.2f}s  
**Generation Parameters:** Temperature={temperature}, Top-p={top_p}, Seed={seed}

## 📊 Executive Summary

| Metric | Value | Status |
|--------|-------|--------|
| **Pass Rate** | {pass_rate:.1f}% | {pass_status} |
| **Average Score** | {avg_score:.2f}/2.0 | {score_status} |
| **Accuracy** | {accuracy:.1f}% | {accuracy_status} |
| **P50 Latency** | {p50_latency:.1f}ms | {latency_status} |
| **P95 Latency** | {p95_latency:.1f}ms | {latency_status} |

**Overall Assessment:** {overall_assessment}

## 🎯 Test Results Breakdown

{test_results_table}

## 📈 Performance Analysis

### Score Distribution
- **Excellent (1.5-2.0):** {excellent_count} tests
- **Good (1.0-1.5):** {good_count} tests  
- **Fair (0.5-1.0):** {fair_count} tests
- **Poor (0.0-0.5):** {poor_count} tests

### Latency Analysis
- **P50 Latency:** {p50_latency:.1f}ms
- **P95 Latency:** {p95_latency:.1f}ms
- **Average Tokens/sec:** {avg_tokens_per_sec:.1f}

## 🔍 Detailed Test Analysis

{detailed_analysis}

## ⚠️ Issues and Warnings

{issues_section}

## 💡 Improvement Suggestions

{improvement_suggestions}

## 📋 Test Categories Performance

{category_analysis}

## 🔧 Technical Details

- **API Endpoint:** {api_url}
- **Test Framework:** Custom Python QA System v{runner_version}
- **Scoring Method:** Weighted criteria (Syntax 40%, Keywords 40%, Libraries 20%)
- **Validation:** Multi-criteria validation with board-specific rules
- **Git Commit:** {git_commit}
- **Model Used:** {model_used}

---

*Report generated by Microcontroller API Assistant QA System*
"""
    
    def generate_report(self, summary, test_suite_name: str, temperature: float = 0.7, 
                       top_p: float = 0.9, seed: int = None) -> str:
        """Generate a comprehensive Markdown report."""
        # Calculate metrics
        metrics = self._calculate_metrics(summary)
        
        # Generate sections
        test_results_table = self._generate_test_results_table(summary.test_results)
        detailed_analysis = self._generate_detailed_analysis(summary.test_results)
        issues_section = self._generate_issues_section(summary.test_results)
        improvement_suggestions = self._generate_improvement_suggestions(summary, metrics)
        category_analysis = self._generate_category_analysis(summary.test_results)
        
        # Get model info from first test result
        model_used = "unknown"
        git_commit = "unknown"
        if summary.test_results:
            first_result = summary.test_results[0]
            if first_result.api_response:
                model_used = first_result.api_response.get("model_used", "unknown")
        
        # Format the report
        report = self.report_template.format(
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            test_suite_name=test_suite_name,
            total_tests=summary.total_tests,
            duration=summary.total_time,
            temperature=temperature,
            top_p=top_p,
            seed=seed if seed is not None else "random",
            pass_rate=metrics["pass_rate"],
            pass_status=metrics["pass_status"],
            avg_score=summary.average_score,
            score_status=metrics["score_status"],
            accuracy=summary.accuracy_percentage,
            accuracy_status=metrics["accuracy_status"],
            p50_latency=summary.p50_latency,
            p95_latency=summary.p95_latency,
            latency_status=metrics["latency_status"],
            overall_assessment=metrics["overall_assessment"],
            test_results_table=test_results_table,
            detailed_analysis=detailed_analysis,
            issues_section=issues_section,
            improvement_suggestions=improvement_suggestions,
            category_analysis=category_analysis,
            api_url="http://localhost:8000",
            runner_version="1.0.0",
            git_commit=git_commit,
            model_used=model_used,
            excellent_count=metrics["excellent_count"],
            good_count=metrics["good_count"],
            fair_count=metrics["fair_count"],
            poor_count=metrics["poor_count"],
            avg_tokens_per_sec=summary.avg_tokens_per_sec,
        )
        
        # Sanitize the report for UTF-8 safety
        report = sanitize_utf8(report)
        
        return report
        
        return report
    
    def _calculate_metrics(self, summary) -> Dict:
        """Calculate comprehensive metrics from test results."""
        results = summary.test_results
        
        # Pass rate
        pass_rate = (summary.passed_tests / summary.total_tests * 100) if summary.total_tests > 0 else 0
        
        # Response times (using latency_ms instead)
        response_times = [r.latency_ms for r in results if r.latency_ms > 0]
        avg_response_time = sum(response_times) / len(response_times) if response_times else 0
        fastest_response = min(response_times) if response_times else 0
        slowest_response = max(response_times) if response_times else 0
        
        # Score distribution
        excellent_count = sum(1 for r in results if r.score >= 1.5)
        good_count = sum(1 for r in results if 1.0 <= r.score < 1.5)
        fair_count = sum(1 for r in results if 0.5 <= r.score < 1.0)
        poor_count = sum(1 for r in results if r.score < 0.5)
        
        # Status indicators
        pass_status = "✅" if pass_rate >= 80 else "⚠️" if pass_rate >= 60 else "❌"
        score_status = "✅" if summary.average_score >= 1.5 else "⚠️" if summary.average_score >= 1.0 else "❌"
        accuracy_status = "✅" if summary.accuracy_percentage >= 75 else "⚠️" if summary.accuracy_percentage >= 50 else "❌"
        latency_status = "✅" if summary.p50_latency <= 3000 else "⚠️" if summary.p50_latency <= 5000 else "❌"
        
        # Overall assessment
        if pass_rate >= 90 and summary.average_score >= 1.5:
            overall_assessment = "🟢 **EXCELLENT** - System performing exceptionally well"
        elif pass_rate >= 75 and summary.average_score >= 1.2:
            overall_assessment = "🟡 **GOOD** - System performing well with minor issues"
        elif pass_rate >= 60 and summary.average_score >= 0.8:
            overall_assessment = "🟠 **FAIR** - System needs improvements"
        else:
            overall_assessment = "🔴 **POOR** - System requires significant improvements"
        
        return {
            "pass_rate": pass_rate,
            "pass_status": pass_status,
            "score_status": score_status,
            "accuracy_status": accuracy_status,
            "latency_status": latency_status,
            "overall_assessment": overall_assessment,
            "excellent_count": excellent_count,
            "good_count": good_count,
            "fair_count": fair_count,
            "poor_count": poor_count,
            "avg_response_time": avg_response_time,
            "fastest_response": fastest_response,
            "slowest_response": slowest_response,
        }
    
    def _generate_test_results_table(self, test_results: List) -> str:
        """Generate a table of test results."""
        table = """
| Test Case | Status | Score | Latency | Tokens/sec | Issues |
|-----------|--------|-------|---------|------------|---------|
"""
        
        for result in test_results:
            status_emoji = "✅" if result.status == "pass" else "⚠️" if result.status == "warn" else "❌"
            issues = ", ".join(result.errors + result.warnings) if result.errors or result.warnings else "None"
            
            table += f"| {result.test_case.name} | {status_emoji} {result.status.upper()} | {result.score:.2f}/2.0 | {result.latency_ms:.0f}ms | {result.tokens_per_sec:.1f} | {issues} |\n"
        
        return table
    
    def _generate_detailed_analysis(self, test_results: List) -> str:
        """Generate detailed analysis of test results."""
        analysis = ""
        
        # Group by status
        passed_tests = [r for r in test_results if r.status == "pass"]
        warned_tests = [r for r in test_results if r.status == "warn"]
        failed_tests = [r for r in test_results if r.status == "fail"]
        
        if passed_tests:
            analysis += "### ✅ Passing Tests\n\n"
            for result in passed_tests[:3]:  # Show top 3
                analysis += f"- **{result.test_case.name}**: {result.test_case.description}\n"
                analysis += f"  - Score: {result.score:.2f}/2.0\n"
                analysis += f"  - Keywords: {', '.join(result.test_case.expected_keywords[:3])}...\n\n"
        
        if warned_tests:
            analysis += "### ⚠️ Tests with Warnings\n\n"
            for result in warned_tests:
                analysis += f"- **{result.test_case.name}**: {result.test_case.description}\n"
                analysis += f"  - Score: {result.score:.2f}/2.0\n"
                analysis += f"  - Warnings: {', '.join(result.warnings)}\n\n"
        
        if failed_tests:
            analysis += "### ❌ Failed Tests\n\n"
            for result in failed_tests:
                analysis += f"- **{result.test_case.name}**: {result.test_case.description}\n"
                analysis += f"  - Score: {result.score:.2f}/2.0\n"
                analysis += f"  - Why it failed: {self._get_failure_reason(result)}\n\n"
        
        return analysis
    
    def _generate_issues_section(self, test_results: List) -> str:
        """Generate issues and warnings section."""
        all_errors = []
        all_warnings = []
        
        for result in test_results:
            all_errors.extend(result.errors)
            all_warnings.extend(result.warnings)
        
        issues_section = ""
        
        if all_errors:
            issues_section += "### 🔴 Critical Issues\n\n"
            for error in set(all_errors):
                count = all_errors.count(error)
                issues_section += f"- **{error}** (occurred {count} times)\n"
            issues_section += "\n"
        
        if all_warnings:
            issues_section += "### 🟡 Warnings\n\n"
            for warning in set(all_warnings):
                count = all_warnings.count(warning)
                issues_section += f"- **{warning}** (occurred {count} times)\n"
            issues_section += "\n"
        
        if not all_errors and not all_warnings:
            issues_section += "### ✅ No Issues Found\n\nAll tests passed without errors or warnings.\n\n"
        
        return issues_section
    
    def _generate_improvement_suggestions(self, summary, metrics: Dict) -> str:
        """Generate improvement suggestions based on test results."""
        suggestions = []
        
        # Score-based suggestions
        if summary.average_score < 1.0:
            suggestions.append("**Improve code generation quality** - Focus on generating more accurate and complete code snippets")
        
        if metrics["poor_count"] > 0:
            suggestions.append("**Address failing test cases** - Review and fix the specific test cases that are scoring poorly")
        
        # Response time suggestions
        if metrics["avg_response_time"] > 5.0:
            suggestions.append("**Optimize response times** - Consider model optimization or caching for faster responses")
        
        # Pass rate suggestions
        if metrics["pass_rate"] < 80:
            suggestions.append("**Increase test coverage** - Add more comprehensive test cases and improve edge case handling")
        
        # Specific suggestions based on common issues
        if any("missing keywords" in str(r.errors) for r in summary.test_results):
            suggestions.append("**Enhance keyword detection** - Improve the model's ability to include expected functions and keywords")
        
        if any("missing libraries" in str(r.errors) for r in summary.test_results):
            suggestions.append("**Improve library inclusion** - Ensure the model includes necessary library headers")
        
        if not suggestions:
            suggestions.append("**Maintain current performance** - The system is performing well, focus on maintaining quality")
        
        suggestions_text = ""
        for i, suggestion in enumerate(suggestions, 1):
            suggestions_text += f"{i}. {suggestion}\n"
        
        return suggestions_text
    
    def _generate_category_analysis(self, test_results: List) -> str:
        """Generate analysis by test category."""
        categories = {}
        
        for result in test_results:
            category = result.test_case.category
            if category not in categories:
                categories[category] = {"total": 0, "passed": 0, "avg_score": 0.0}
            
            categories[category]["total"] += 1
            if result.status == "pass":
                categories[category]["passed"] += 1
            categories[category]["avg_score"] += result.score
        
        # Calculate averages
        for category in categories:
            total = categories[category]["total"]
            categories[category]["avg_score"] /= total
            categories[category]["pass_rate"] = (categories[category]["passed"] / total) * 100
        
        category_text = "| Category | Tests | Pass Rate | Avg Score | Status |\n"
        category_text += "|----------|-------|-----------|-----------|--------|\n"
        
        for category, stats in categories.items():
            status = "✅" if stats["pass_rate"] >= 80 else "⚠️" if stats["pass_rate"] >= 60 else "❌"
            category_text += f"| {category} | {stats['total']} | {stats['pass_rate']:.1f}% | {stats['avg_score']:.2f} | {status} |\n"
        
        return category_text
    
    def _get_failure_reason(self, result) -> str:
        """Get a concise reason why a test failed."""
        if result.errors:
            # Check for specific validation failures
            for error in result.errors:
                if "missing keywords" in error.lower():
                    return "Missing expected keywords/functions"
                elif "missing libraries" in error.lower():
                    return "Missing required libraries"
                elif "board_specific" in error.lower():
                    return "Board-specific API mismatch"
                elif "api_schema" in error.lower():
                    return "API response schema error"
                elif "syntax" in error.lower():
                    return "Code syntax issues"
            
            return result.errors[0]  # Return first error
        
        if result.warnings:
            return result.warnings[0]  # Return first warning
        
        if result.score < 0.5:
            return "Very low score - significant issues detected"
        elif result.score < 1.0:
            return "Low score - code quality issues"
        
        return "Unknown failure reason"


if __name__ == "__main__":
    # Test the reporter
    from runner import TestResult, TestSummary, TestCase
    from cases import MicrocontrollerType
    
    # Create a mock test result
    test_case = TestCase(
        name="Test_LED_Control",
        prompt="How to control LED on Arduino?",
        microcontroller_type=MicrocontrollerType.ARDUINO_UNO,
        expected_keywords=["pinMode", "digitalWrite"],
        expected_libraries=[],
        description="LED control test",
        category="gpio",
        difficulty="easy"
    )
    
    test_result = TestResult(
        test_case=test_case,
        input_prompt="How to control LED on Arduino?",
        generated_code="void setup() { pinMode(13, OUTPUT); } void loop() { digitalWrite(13, HIGH); }",
        response_time=1.5,
        score=1.8,
        score_breakdown={"syntax": 0.8, "keywords": 1.0, "libraries": 0.5},
        validation_results={"syntax": True, "critical_keywords": True, "expected_keywords": True},
        warnings=[],
        errors=[],
        status="pass"
    )
    
    summary = TestSummary(
        total_tests=1,
        passed_tests=1,
        warned_tests=0,
        failed_tests=0,
        average_score=1.8,
        total_time=1.5,
        test_results=[test_result]
    )
    
    reporter = ReportGenerator()
    report = reporter.generate_report(summary, "test_suite")
    print(report)
